[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.6.0
    https://github.com/AaronLiddiment/LEDMatrix
    https://github.com/AaronLiddiment/LEDText
    bblanchon/ArduinoJson @ ^7

